### ISSUE TITLE
Better Documentation 

### ISSUE THREAD

**Issue by pspiagicw** [amake/org_parser#10]
The example file is not thorough enough.
Can you include more documentation on how to use it. 
By the way , Great work! This app really helps me on my notes !

**Comment by amake** [comment]
Thanks for the kind words.

Can you give me an example of what you'd like to use this library to do? That would help me think of a better example.

**Comment by pspiagicw** [comment]
My idea is to build a org-agenda type app for android. Right now it only lists the todo's in a list.  I need the library to extract all the todo's given in the files , along with their description and probably their deadline/scheduled times.

**Comment by amake** [comment]
Nice. I assume you're making the app with Flutter?

**Comment by pspiagicw** [comment]
Yes , although I am new to it.

**Comment by amake** [comment]
I added a bunch of comments in https://github.com/amake/org_parser/commit/3c68642496579561a5252ab5ec138ac4f8be6c54 and expanded the example in https://github.com/amake/org_parser/commit/7902c9a24135e4ef80ebfcf0fc8322dee303cf34.

Does that give you what you need?

Unfortunately right now there isn't an easy way to go from parsed AST back to markup, so it's a bit of a pain to get at something like a headline title, which is not readily available as a string (headline titles can contain markup for styling, links, etc.).

If you're looking to display Org Mode content in your app, you should look at https://github.com/amake/org_flutter. You can use the individual widgets piecemeal instead of displaying the whole document if you like.

**Comment by pspiagicw** [comment]
Thanks! It would help me a lot!

**Comment by amake** [comment]
I'm going to call this done. If anything more is needed please reopen.
